Fix token and exit if error

diff --git a/.github/workflows/integrity.yml b/.github/workflows/integrity.yml
--- a/.github/workflows/integrity.yml
+++ b/.github/workflows/integrity.yml
@@ -58,7 +58,7 @@ jobs:
       - name: Notify status
         if: always()
         env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKE }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GITHUB_REPOSITORY: ${{ github.repository }}
           GITHUB_ACTOR: ${{ github.actor }}
           GITHUB_REF: ${{ github.ref }}
@@ -72,5 +72,9 @@ jobs:
           curl -X POST -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/${{ github.repository }}/issues/1/comments \
           -d "{\"body\": \"$COMMENT\"}"
+          if grep -qi "ERROR" $ERROR_LINES; then
+            echo "Falló la prueba"
+            exit 1
+          fi
 
       
