Check for error and exit if any

diff --git a/.github/workflows/integrity.yml b/.github/workflows/integrity.yml
--- a/.github/workflows/integrity.yml
+++ b/.github/workflows/integrity.yml
@@ -59,12 +59,16 @@ jobs:
           GITHUB_SHA: ${{ github.sha }}
           ERROR_LINES: ${{ env.ERROR_LINES }}
         run: |
-          COMMENT=$(printf "Branch: %s\nUsuario: %s\nCommit: %s Algún error: %s" "$GITHUB_REF" "$GITHUB_ACTOR" "$GITHUB_SHA" "$ERROR_LINES")
+          COMMENT=$(printf "Branch: %s\nUsuario: %s\nCommit: %s\n Algún error: \n%s" "$GITHUB_REF" "$GITHUB_ACTOR" "$GITHUB_SHA" "$ERROR_LINES")
 
           echo $COMMENT
 
           curl -X POST -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/${{ github.repository }}/issues/1/comments \
           -d "$(jq -nc --arg body "$COMMENT" '{"body": $body}')"
+
+          if grep -q "ERROR:" test_output.txt; then
+            exit 1
+          fi          
 
       
